window.Bahasa = {
    
    "indonesia": {
        code: "id",
        dashboard: {
            navbarPesan: "message",
            navbarRandom: "random",
            navbarGrup: "group",
            navbarKiriman: "posts",
            navbarHome: "Home",
            navbarAddItem: "Add Item",
            navbarAula: "aula",
            optProfil: "profile",
            optTema: "theme",
            optLibrary: "library",
            optLaporkan: "report",
            optKeluar: "LogOut",
            notipinLaporkan: "DESCRIBE THE INTERESTING THINGS (BUGS/LESS GOOD THINGS) YOU FOUND",
            notipinTema: "WANT TO CHANGE THEME?",
            notipinKeluar: "DO YOU REALLY WANT TO EXIT YOUR ACCOUNT?",
            notipinLaporkan_Sukses: "RESULTS REPORT SENT!",
        },
        aula: {
            nomore: "THERE ARE NO OTHER PROMOTIONS",
            tombolBuat: "make a promotion",
            inputGambar: "Select Picture",
            inputJudul: "Project title",
            inputDeskripsi: "Short Description",
            inputLink: "Link/URL -- https:// --",
            tombolBatal: "CANCELLED",
            tombolLanjut: "SEND",
            notipinFileGambar: "PLEASE CHOOSE THE PHOTO THAT DESCRIBES YOUR PROJECT",
            notipinTipeGambar: "SELECT FILE WITH IMAGE TYPE DONG",
            notipinInput: "SELECT FILE WITH IMAGE TYPE DONG",
            notipinLink: "PLEASE COMPLETE THE LINK WITH THE CORRECT FORMAT",
            notipinSubmit: "PROMOTION WILL NOT DISAPPEAR FOREVER AFTER SENT<br/>STILL WANT TO CONTINUE?"
        },
        cari: {
            judul: "Search Users",
            inputNama: "Write Name",
            tombolBatal: "CANCELLED",
            tombolLanjut: "LOOK FOR",
            notipinKarakter: "ENTER MINIMUM 2 CHARACTERS TO SEARCH",
            nomore: "THERE ARE NO OTHER SEARCH RESULTS",
        },
        chat: {
            inputPesan: "Write a Message . . .",
            pesanTerhapus: "Message Has Been Deleted",
            kirimVN: "Processing Recordings...",
            kirimGambar: "Uploading...",
            notipinTipeGambar: "SELECT FILE WITH IMAGE TYPE",
            notipinTarik: "Are you sure you want to delete this message?",
        },
        list_grup: {
            nomore: "THERE ARE NO OTHER GROUPS THAT YOU HAVE FOLLOWED",
            tombolBuat: "CREATE A GROUP",
            tombolGabung: "JOIN",
            judulBuat: "Create a Group",
            judulGabung: "JOIN THE GROUP",
            inputNama: "Group Name",
            inputID: "ID Group",
            tombolBatal: "CANCELLED",
            tombolLanjut_Buat: "MAKE",
            tombolLanjut_Gabung: "JOIN",
            notipinGagal: "COULD NOT FIND THE GROUP",
        },
        list_pesan: {
            nomore: "NO OTHER RESULTS",
        },
        list_post: {
            tombolBuat: "CREATE A POST",
            notipinHapus: "DO YOU WANT TO DELETE THIS POST?",
            inputPesan: "Type Here..",
            notipinTarik: "DO YOU WANT TO DELETE THIS COMMENT?",
            pilihPublik: "PUBLIC",
            pilihfollowers: "FOLLOWERS",
            inputGambar: "Choose Picture",
            inputSesuatu: "Type Here",
            tombolBatal: "CANCEL",
            tombolLanjut: "SUBMIT",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
        },
        guild: {
            tombolTutup: "Close",
            tombolChat: "Chat",
            tombolKeluar: "Leave Grup",
            anggota: "Member(s)",
            notipinKeluar: "ARE YOU SURE YOU WANT TO LEAVE THIS GROUP",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
        },
        pengguna: {
            tombolIkuti: "Follow",
            tombolMengikuti: "Followed",
            tombolChat: "Chat",
            tombolTutup: "Close",
            notipinBerhenti: "DO YOU WANT TO UNFOLLOW THIS USER?",
            followers: "Follower"
        },
        profil: {
            tombolSelesai: "Done",
            followers: "Followers",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
            inputUsername: "Write Username",
            inputBio: "Write Here",
            tombolSimpan: "SAVE",
            tombolBatal: "CANCEL",
            notipinUsername: "WRITE MINIMUM 4 CHARACTERS",
        },
        random: {
            judul: "Find Random Users Online!",
            tombolLanjut: "Find Now",
            notipinPengguna: "No active users found<br/>Do you want to continue with offline users?",
        },
    },
    "english": {
        code: "en",
        dashboard: {
            navbarPesan: "chats",
            navbarRandom: "random",
            navbarGrup: "groups",
            navbarKiriman: "posts",
            navbarAula: "hall",
            optProfil: "profile",
            optTema: "theme",
            optLibrary: "library",
            optLaporkan: "report",
            optKeluar: "logout",
            notipinLaporkan: "DESCRIBE HERE",
            notipinTema: "WANT TO CHANGE THE THEME?",
            notipinKeluar: "LOGOUT NOW?",
            notipinLaporkan_Sukses: "THANK YOU FOR REPORTING!",
        },
        aula: {
            nomore: "THERE'S NO MORE",
            tombolBuat: "create now",
            inputGambar: "Choose Picture",
            inputJudul: "Project's Title",
            inputDeskripsi: "Short Description",
            inputLink: "Link/URL -- https:// --",
            tombolBatal: "CANCEL",
            tombolLanjut: "SUBMIT",
            notipinFileGambar: "PLEASE CHOOSE A PICTURE ABOUT THE PROJCET YOU'VE MADE",
            notipinTipeGambar: "IMAGE FILE ONLY",
            notipinInput: "FILL IN THE BLANKS",
            notipinLink: "PLEASE FILL IN THE LINK WITH THE CORRECT FORMAT",
            notipinSubmit: "THE PROMOTION WILL PERMANENTLY ONLINE AFTER SUBMITTED<br/>CONTINUE ANYWAY?"
        },
        cari: {
            judul: "Find People",
            inputNama: "Type Here",
            tombolBatal: "CANCEL",
            tombolLanjut: "GO",
            notipinKarakter: "WRITE MINIMUM 2 CHARACTERS TO FIND",
            nomore: "NO RESULT FOUND",
        },
        chat: {
            inputPesan: "Type Here . . .",
            pesanTerhapus: "Message Has Been Deleted",
            kirimVN: "Converting Audio File...",
            kirimGambar: "Uploading...",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
            notipinTarik: "DO YOU WANT TO DELETE THIS MESSAGE?",
        },
        list_grup: {
            nomore: "THERE ARE NO OTHER GROUPS YOU HAVE PARTICIPATED",
            tombolBuat: "CREATE A GROUP",
            tombolGabung: "JOIN A GROUP",
            judulBuat: "Group Creation",
            judulGabung: "Group Join",
            inputNama: "Group Name",
            inputID: "Group ID",
            tombolBatal: "CANCEL",
            tombolLanjut_Buat: "CREATE",
            tombolLanjut_Gabung: "JOIN",
            notipinGagal: "CAN'T FIND THE GROUP",
        },
        list_pesan: {
            nomore: "NO RESULT FOUND",
        },
        list_post: {
            tombolBuat: "CREATE A POST",
            notipinHapus: "DO YOU WANT TO DELETE THIS POST?",
            inputPesan: "Type Here..",
            notipinTarik: "DO YOU WANT TO DELETE THIS COMMENT?",
            pilihPublik: "PUBLIC",
            pilihfollowers: "FOLLOWERS",
            inputGambar: "Choose Picture",
            inputSesuatu: "Type Here",
            tombolBatal: "CANCEL",
            tombolLanjut: "SUBMIT",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
        },
        guild: {
            tombolTutup: "Close",
            tombolChat: "Chat",
            tombolKeluar: "Leave Grup",
            anggota: "Member(s)",
            notipinKeluar: "ARE YOU SURE YOU WANT TO LEAVE THIS GROUP",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
        },
        pengguna: {
            tombolIkuti: "Follow",
            tombolMengikuti: "Followed",
            tombolChat: "Chat",
            tombolTutup: "Close",
            notipinBerhenti: "DO YOU WANT TO UNFOLLOW THIS USER?",
            followers: "Follower"
        },
        profil: {
            tombolSelesai: "Done",
            followers: "Followers",
            notipinTipeGambar: "CHOOSE IMAGE FILE ONLY",
            inputUsername: "Write Username",
            inputBio: "Write Here",
            tombolSimpan: "SAVE",
            tombolBatal: "CANCEL",
            notipinUsername: "WRITE MINIMUM 4 CHARACTERS",
        },
        random: {
            judul: "Find Random Users Online!",
            tombolLanjut: "Find Now",
            notipinPengguna: "No active users found<br/>Do you want to continue with offline users?",
        },
    }
}

/*
    SUBSCRIBE: DEVANKA 761 
    https://www.youtube.com/c/RG761

    IG: " @dvnkz_ "
*/